CREATE TABLE "Roles" (
  "roles_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar(20) NOT NULL
);

CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20) NOT NULL,
  "password" varchar(100) NOT NULL,
  "mail" varchar(30) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "role_id" int
);

CREATE TABLE "Image" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" varchar(255) NOT NULL,
  "coordinates_x" number NOT NULL,
  "coordinates_y" number NOT NULL,
  "user_id" int,
  "tag_id" int
);

CREATE TABLE "Save" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "image_id" int
);

CREATE TABLE "Tag" (
  "tag_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

CREATE TABLE "ClothingType" (
  "clothing_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "Clothing" (
  "clothing_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "size" number NOT NULL,
  "color" int NOT NULL,
  "clothing_type_id" int
);

CREATE TABLE "Location" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "ClothingDesign" (
  "clothing_design_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image_id" int,
  "clothing_id" int,
  "location_id" int
);

CREATE TABLE "Subscraib" (
  "subscraib_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "folower_user_id" int,
  "target_user_id" int
);

CREATE TABLE "Notification" (
  "notification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" varchar(255) NOT NULL,
  "timestamp" data NOT NULL,
  "subscraib_id" int
);

ALTER TABLE "User" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("roles_id");

ALTER TABLE "Image" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Image" ADD FOREIGN KEY ("tag_id") REFERENCES "Tag" ("tag_id");

ALTER TABLE "Save" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Save" ADD FOREIGN KEY ("image_id") REFERENCES "Image" ("image_id");

ALTER TABLE "Clothing" ADD FOREIGN KEY ("clothing_type_id") REFERENCES "ClothingType" ("clothing_type_id");

ALTER TABLE "ClothingDesign" ADD FOREIGN KEY ("image_id") REFERENCES "Image" ("image_id");

ALTER TABLE "ClothingDesign" ADD FOREIGN KEY ("clothing_id") REFERENCES "Clothing" ("clothing_id");

ALTER TABLE "ClothingDesign" ADD FOREIGN KEY ("location_id") REFERENCES "Location" ("location_id");

ALTER TABLE "Subscraib" ADD FOREIGN KEY ("folower_user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Subscraib" ADD FOREIGN KEY ("target_user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("subscraib_id") REFERENCES "Subscraib" ("subscraib_id");
